import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import Script from "next/script";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const MEASUREMENT_ID = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${MEASUREMENT_ID}`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${MEASUREMENT_ID}');
          `}
        </Script>

      </head>
     
      <body
        className="antialiased">
        <Providers>
            {children}
          </Providers>
      </body>
    </html>
  );
}

